apiVersion: v1
kind: Service
metadata:
  name: esgame-angular-service
  labels:
    app: esgame-angular
spec:
  type: ClusterIP
  selector:
    app: esgame-angular
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
