apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: esgame-angular-ingress
  labels:
    app: esgame-angular
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
    - host: CHANGE-ME-esgame.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: esgame-angular-service
                port:
                  number: 80
