#!/usr/bin/env bash
# Produce a table of what the model scores for a set of contrasting landscapes, for someone who
# knows the ecology to look at and say "that is wrong".
#
# WHY THIS EXISTS
#
# Nothing in this repository can tell you the model is right. tools/R/golden-test.sh freezes the
# current answers so a change is noticed, which is a different thing — it would happily freeze a
# wrong answer. The only way to learn whether the numbers are sensible is for a domain expert to
# read them, and asking that of someone means handing them numbers, not an R prompt and a Docker
# daemon.
#
# So: one round per scenario, against a running calculator, printed as markdown. Paste it into an
# email or an issue.
#
#   BASE=http://localhost:8880 CALC_HOST=esgame-calculation.local tools/R/scores-sheet.sh
#   ... tools/R/scores-sheet.sh > scores-sheet.md
#
# Takes a few minutes: each scenario is a real round (12-30s) and they cannot overlap, because the
# backend is single-threaded (see perf/README.md).
set -euo pipefail
cd "$(dirname "$0")/../.."

BASE="${BASE:-http://localhost:8880}"
CALC_HOST="${CALC_HOST:-esgame-calculation.local}"

# The six production types the game offers, from v2/src/assets/data.json.
#   10 Extensive Arable   20 Intensive Arable   30 Extensive Livestock
#   40 Intensive Livestock  50 Agropark         60 Extra Nature
#
# Uniform landscapes first, because they are the ones with an obvious expected direction: whatever
# "intensive everything" does to nutrient pollution, it should not do the same as "nature
# everywhere". Then two mixtures a player might actually build.
SCENARIOS=(
  "all-extensive-arable|uniform|10|Every hexagon extensive arable."
  "all-intensive-arable|uniform|20|Every hexagon intensive arable. Expect the worst pollution numbers."
  "all-extensive-livestock|uniform|30|Every hexagon extensive livestock."
  "all-intensive-livestock|uniform|40|Every hexagon intensive livestock."
  "all-agropark|uniform|50|Every hexagon agropark."
  "all-nature|uniform|60|Every hexagon extra nature. No agriculture at all."
  "half-intensive-half-nature|alternate|20:60|Alternating intensive arable and nature."
  "mostly-nature-some-farms|ratio|10:60:46|46 of 465 extensive arable, the rest nature — roughly what a cautious player builds."
)

say() { printf '%s\n' "$1"; }

say "# esgame — what the model scores for contrasting landscapes"
say ""
say "Generated by \`tools/R/scores-sheet.sh\` against a live calculator."
say "Board: 465 hexagons. Base raster: \`v2/src/assets/images/LU_and_NEW_hexa.tif\`."
say ""
say "**Please read the two caveats under the table before judging any number.**"
say ""
say "| Landscape | Human health | Nutrient pollution | Water availability | Habitat cohesion | Recreational |"
say "|---|---|---|---|---|---|"

notes=()
for entry in "${SCENARIOS[@]}"; do
  IFS='|' read -r name kind spec desc <<< "${entry}"
  python3 - "${kind}" "${spec}" "${name}" > /tmp/sheet-payload.json <<'PY'
import json, sys
kind, spec, name = sys.argv[1], sys.argv[2], sys.argv[3]
ids = [i * 100 for i in range(1, 466)]
if kind == "uniform":
    lulc = [int(spec)] * len(ids)
elif kind == "alternate":
    a, b = (int(x) for x in spec.split(":"))
    lulc = [a if k % 2 == 0 else b for k in range(len(ids))]
else:                                   # ratio: first:rest:count
    a, b, n = (int(x) for x in spec.split(":"))
    lulc = [a if k < n else b for k in range(len(ids))]
print(json.dumps({"allocation": [{"id": i, "lulc": l} for i, l in zip(ids, lulc)],
                  "round": 1, "score": 1, "game_id": "sheet-" + name}))
PY
  body=$(mktemp)
  code=$(curl -s -o "${body}" -w '%{http_code}' --max-time 600 \
    -H "Host: ${CALC_HOST}" -H 'Content-Type: application/json' \
    --data @/tmp/sheet-payload.json "${BASE}/esgame" || echo 000)
  row=$(python3 - "${body}" "${code}" "${name}" <<'PY'
import json, sys
body, code, name = sys.argv[1], sys.argv[2], sys.argv[3]
order = ["HH", "NP", "WA", "HC", "RV"]
if code != "200":
    print(f"| `{name}` | " + " | ".join(["_no answer_"] * 5) + " |"); raise SystemExit
d = json.load(open(body))
s = {r["name"].split("_")[0]: r.get("score") for r in d.get("results", []) if r.get("id") != -1}
def cell(k):
    v = s.get(k)
    if v is None: return "_missing_"
    if isinstance(v, float) and v != v: return "**NaN**"
    return str(v)
print(f"| `{name}` | " + " | ".join(cell(k) for k in order) + " |")
PY
)
  say "${row}"
  notes+=("- \`${name}\` — ${desc}")
  rm -f "${body}"
done

say ""
say "## What each landscape is"
say ""
for n in "${notes[@]}"; do say "${n}"; done
say ""
say "## Two caveats, both of which affect how you should read the table"
say ""
say "**1. The scores are relative to each round, not to an absolute scale.** Every indicator is"
say "normalised \`(x - min) / (max - min) * 100\` over that round's own surface, so a value near 50"
say "means \"about average *for this landscape*\", not \"moderate in absolute terms\". A landscape"
say "of uniformly mild pollution and one of uniformly severe pollution can both average near 50."
say "Comparing rows may therefore be less meaningful than it looks — this is the single thing most"
say "worth a second opinion."
say ""
say "**2. NaN is a real result, not a crash.** It appears when an indicator's surface ends up empty"
say "or uniform, because the normalisation above then divides by zero. \`all-nature\` reaches it: with"
say "no agriculture there is no agricultural pollution anywhere, so human health has no cells left"
say "to score. What it *should* say instead is a modelling question, which is part of what this"
say "sheet is asking."

say ""
say "## Questions worth answering while you read it"
say ""
say "These are the things the people who built the harness cannot judge:"
say ""
say "1. **Do the five indicators move independently, or together?** This is a *tradeoff* game, so"
say "   the interesting case is a landscape that improves one indicator and worsens another. If"
say "   every column rises and falls as one, there is nothing for a player to trade off, and that"
say "   would be worth knowing before a workshop rather than during one."
say "2. **Is the direction right?** For each indicator, does the landscape you would expect to score"
say "   worst actually score worst? A sign error would be invisible to every test in this repository."
say "3. **Is the spread usable?** If every landscape lands within a few points, players will not see"
say "   their choices reflected, whatever the model does internally."
say "4. **Is NaN acceptable for \`all-nature\`, or should it be a number?** See caveat 2. Note that"
say "   PLACES' \`calculation.r\` normalises every indicator against *fixed* bounds rather than"
say "   against the round, so it cannot produce this NaN and its scores *are* comparable between"
say "   rounds. Whether esgame should do the same is the question underneath all of the above."
