#!/usr/bin/env bash
# Produce a table of what the model scores for a set of contrasting landscapes, for someone who
# knows the ecology to look at and say "that is wrong".
#
# WHY THIS EXISTS
#
# Nothing in this repository can tell you the model is right. tools/R/golden-test.sh freezes the
# current answers so a change is noticed, which is a different thing — it would happily freeze a
# wrong answer. The only way to learn whether the numbers are sensible is for a domain expert to
# read them, and asking that of someone means handing them numbers, not an R prompt and a Docker
# daemon.
#
# So: one round per scenario, against a running calculator, printed as markdown. Paste it into an
# email or an issue.
#
#   BASE=http://localhost:8880 CALC_HOST=esgame-calculation.local tools/R/scores-sheet.sh
#   ... tools/R/scores-sheet.sh > scores-sheet.md
#
# Takes a few minutes: each scenario is a real round (12-30s) and they cannot overlap, because the
# backend is single-threaded (see perf/README.md).
set -euo pipefail
cd "$(dirname "$0")/../.."

BASE="${BASE:-http://localhost:8880}"
CALC_HOST="${CALC_HOST:-esgame-calculation.local}"

# The six production types the game offers, from v2/src/assets/data.json.
#   10 Extensive Arable   20 Intensive Arable   30 Extensive Livestock
#   40 Intensive Livestock  50 Agropark         60 Extra Nature
#
# Uniform landscapes first, because they are the ones with an obvious expected direction: whatever
# "intensive everything" does to nutrient pollution, it should not do the same as "nature
# everywhere". Then two mixtures a player might actually build.
SCENARIOS=(
  "all-extensive-arable|uniform|10|Every hexagon extensive arable."
  "all-intensive-arable|uniform|20|Every hexagon intensive arable. Expect the worst pollution numbers."
  "all-extensive-livestock|uniform|30|Every hexagon extensive livestock."
  "all-intensive-livestock|uniform|40|Every hexagon intensive livestock."
  "all-agropark|uniform|50|Every hexagon agropark."
  "all-nature|uniform|60|Every hexagon extra nature. No agriculture at all."
  "half-intensive-half-nature|alternate|20:60|Alternating intensive arable and nature."
  "mostly-nature-some-farms|ratio|10:60:46|46 of 465 extensive arable, the rest nature — roughly what a cautious player builds."
)

say() { printf '%s\n' "$1"; }

say "# esgame — what the model scores for contrasting landscapes"
say ""
# Stamped by the generator, not by hand. The committed sample carried a hand-written date and
# commit, and its caveats then described the pre-2026-08-07 scoring for a week — a provenance
# line nothing re-derives is the same defect in miniature.
say "Generated by \`tools/R/scores-sheet.sh\` against a live calculator on **$(date -u +%Y-%m-%d)**,"
say "at \`$(git rev-parse --short HEAD 2>/dev/null || echo unknown)\`. Re-run it for current numbers."
say "Board: 465 hexagons. Base raster: \`v2/src/assets/images/LU_and_NEW_hexa.tif\`."
say ""
say "**Read the two notes under the table before judging any number** — in particular, the scale"
say "changed on 2026-08-07 and older copies of this sheet describe the old one."
say ""
say "| Landscape | Human health | Nutrient pollution | Water availability | Habitat cohesion | Recreational |"
say "|---|---|---|---|---|---|"

notes=()
for entry in "${SCENARIOS[@]}"; do
  IFS='|' read -r name kind spec desc <<< "${entry}"
  python3 - "${kind}" "${spec}" "${name}" > /tmp/sheet-payload.json <<'PY'
import json, sys
kind, spec, name = sys.argv[1], sys.argv[2], sys.argv[3]
ids = [i * 100 for i in range(1, 466)]
if kind == "uniform":
    lulc = [int(spec)] * len(ids)
elif kind == "alternate":
    a, b = (int(x) for x in spec.split(":"))
    lulc = [a if k % 2 == 0 else b for k in range(len(ids))]
else:                                   # ratio: first:rest:count
    a, b, n = (int(x) for x in spec.split(":"))
    lulc = [a if k < n else b for k in range(len(ids))]
print(json.dumps({"allocation": [{"id": i, "lulc": l} for i, l in zip(ids, lulc)],
                  "round": 1, "score": 1, "game_id": "sheet-" + name}))
PY
  body=$(mktemp)
  code=$(curl -s -o "${body}" -w '%{http_code}' --max-time 600 \
    -H "Host: ${CALC_HOST}" -H 'Content-Type: application/json' \
    --data @/tmp/sheet-payload.json "${BASE}/esgame" || echo 000)
  row=$(python3 - "${body}" "${code}" "${name}" <<'PY'
import json, sys
body, code, name = sys.argv[1], sys.argv[2], sys.argv[3]
order = ["HH", "NP", "WA", "HC", "RV"]
if code != "200":
    print(f"| `{name}` | " + " | ".join(["_no answer_"] * 5) + " |"); raise SystemExit
d = json.load(open(body))
s = {r["name"].split("_")[0]: r.get("score") for r in d.get("results", []) if r.get("id") != -1}
def cell(k):
    v = s.get(k)
    if v is None: return "_missing_"
    if isinstance(v, float) and v != v: return "**NaN**"
    return str(v)
print(f"| `{name}` | " + " | ".join(cell(k) for k in order) + " |")
PY
)
  say "${row}"
  notes+=("- \`${name}\` — ${desc}")
  rm -f "${body}"
done

say ""
say "## What each landscape is"
say ""
for n in "${notes[@]}"; do say "${n}"; done
say ""
say "## Two things to know before you read the table"
say ""
say "**1. The rows ARE comparable with each other.** Each indicator is normalised against fixed"
say "bounds held in \`tools/R/bounds.json\`, so 60 means the same exposure in every row and in every"
say "round. The bounds come from running this model over two extreme allocations — every hexagon"
say "nature (the floor) and every hexagon agropark (the ceiling) — so the scale is anchored to what"
say "this model can actually produce on this base raster, not to an arbitrary constant."
say ""
say "This changed on 2026-08-07. Scores used to be normalised over each round's own surface, and"
say "under that scheme the rows were NOT comparable, \`all-nature\` returned NaN by dividing by zero,"
say "and the ranking was inverted — all-agropark scored BETTER for human health than"
say "all-extensive-arable, because the only thing that differed was how many cells fell under the"
say "floor. If you are holding an older copy of this sheet, that is what its caveats describe."
say ""
say "**2. What the map shows is a different scale, still.** The published rasters are stretched to"
say "each round's own min and max, so the colour ramp answers \"where, within this round?\" while the"
say "score answers \"how does this round compare?\". That split is deliberate and open — see \"Should"
say "the published rasters move to the same fixed scale as the scores?\" in"
say "docs/verification-status.rst. It does not affect the numbers below."

say ""
say "## Questions worth answering while you read it"
say ""
say "These are the things the people who built the harness cannot judge:"
say ""
say "1. **Do the five indicators move independently, or together?** This is a *tradeoff* game, so"
say "   the interesting case is a landscape that improves one indicator and worsens another. If"
say "   every column rises and falls as one, there is nothing for a player to trade off, and that"
say "   would be worth knowing before a workshop rather than during one."
say "2. **Is the direction right?** For each indicator, does the landscape you would expect to score"
say "   worst actually score worst? A sign error would be invisible to every test in this repository."
say "3. **Is the spread usable?** If every landscape lands within a few points, players will not see"
say "   their choices reflected, whatever the model does internally."
say "4. **Is 0 right for \`all-nature\`?** A landscape with no agriculture has no agricultural"
say "   exposure, so every indicator scores 0 — the floor the bounds were derived from. It used to"
say "   return NaN here. 0 is defensible as \"no exposure\", but whether a player should see the best"
say "   possible landscape scoring zero on every axis is a design question, not a modelling one."
